// AUTO-GENERATED by scripts/import-wc.mjs — do not edit by hand
// (Extended manually with `gallery` field — optional, populated via admin DB override)
import data from "@/data/Mproduse.json";
import type { MediaItem } from "@/lib/media";
import type { ProductSpec } from "@/lib/product-specs";

export type Product = {
  sku: string;
  slug: string;
  name: string;
  shortSpec: string;
  description: string;
  category: string;
  subcategory?: string;
  subSubcategory?: string;
  image: string;
  /** Alt text pentru imaginea principală (default: numele produsului). */
  imageAlt?: string;
  datasheetUrl: string;
  descriptionBlocks: DescriptionBlock[];
  seoTitle: string;
  seoDescription: string;
  focusKeyword: string;
  /** Galerie media adițională: 0-8 imagini + YouTube embeds. Populată via admin override. */
  gallery?: MediaItem[];
  /** Override specs highlight pentru hero — dacă lipsește, se auto-extrag. */
  specs?: ProductSpec[];
  /**
   * Preț de pornire (configurație de bază). Format cu "De la €X.XXX + TVA".
   * Dacă lipsește → afișează doar CTA "Cere ofertă" (fără preț).
   */
  priceFrom?: number;
  /** Moneda prețului afișat. Default: EUR. */
  priceCurrency?: "EUR" | "RON" | "USD";
  /** Preț TVA-inclus sau plus TVA. Default: false (B2B standard). */
  priceIncludesVAT?: boolean;
  /** Notă clarificativă sub preț (ex: "configurație de bază"). */
  priceNote?: string;
};

export type DescriptionBlock =
  | { type: "paragraph"; text: string }
  | { type: "table"; rows: string[][] };

export const PRODUCTS: Product[] = data as Product[];
