// AUTO-GENERATED by scripts/import-wc.mjs — do not edit by hand
// (Extended manually with `gallery` field — optional, populated via admin DB override)
import data from "@/data/produse.json";
import type { MediaItem } from "@/lib/media";

export type Product = {
  sku: string;
  slug: string;
  name: string;
  shortSpec: string;
  description: string;
  category: string;
  subcategory?: string;
  subSubcategory?: string;
  image: string;
  /** Alt text pentru imaginea principală (default: numele produsului). */
  imageAlt?: string;
  datasheetUrl: string;
  descriptionBlocks: DescriptionBlock[];
  seoTitle: string;
  seoDescription: string;
  focusKeyword: string;
  /** Galerie media adițională: 0-8 imagini + YouTube embeds. Populată via admin override. */
  gallery?: MediaItem[];
};

export type DescriptionBlock =
  | { type: "paragraph"; text: string }
  | { type: "table"; rows: string[][] };

export const PRODUCTS: Product[] = data as Product[];
