// AUTO-GENERATED by scripts/import-wc.mjs — do not edit by hand
import data from "@/data/produse.json";

export type Product = {
  sku: string;
  slug: string;
  name: string;
  shortSpec: string;
  description: string;
  category: string;
  subcategory?: string;
  subSubcategory?: string;
  image: string;
  datasheetUrl: string;
  descriptionBlocks: DescriptionBlock[];
  seoTitle: string;
  seoDescription: string;
  focusKeyword: string;
};

export type DescriptionBlock =
  | { type: "paragraph"; text: string }
  | { type: "table"; rows: string[][] };

export const PRODUCTS: Product[] = data as Product[];
